# Generated by Django 5.2.1 on 2025-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('Industry', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Type_of_Work', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Employment_type', models.JSONField(default=list)),
                ('Operating_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('Requirements', models.JSONField(default=list)),
                ('Url', models.CharField(max_length=300)),
            ],
        ),
    ]
